// write_openjscad.ts

import type { tContour } from './contour';
import type { tFaces } from './figure';
import type { tOpenjscadSeg } from './prepare_openjscad';
import type { tVolume, tExtrude, tBVolume } from './volume';
import { EExtrude, EBVolume } from './volume';

// floating precision for OpenScad export
function ff(ifloat: number): string {
	return ifloat.toFixed(4);
}

class OjscadWriteFigure {
	pts: Array<string>;
	constructor() {
		this.pts = [];
	}
	addContour(ictr: tOpenjscadSeg) {
		const pts2: Array<string> = [];
		for (const pt of ictr) {
			const [px, py] = pt;
			pts2.push(`[ ${ff(px)}, ${ff(py)} ]`);
		}
		const ptStr = `[ ${pts2.join(',')} ]`;
		this.pts.push(ptStr);
	}
	getFigure(faceId: string): string {
		let rStr = '';
		const aList: Array<string> = [];
		for (const idx of this.pts.keys()) {
			const aId = `ctr_${faceId}_${idx}`;
			rStr += `const ${aId} = polygon({ points: ${this.pts[idx]} });\n`;
			aList.push(aId);
		}
		if (aList.length === 1) {
			rStr += `const face_${faceId} = ctr_${faceId}_0;\n`;
		} else {
			const ctrList = aList.join(', ');
			rStr += `const face_${faceId} = subtract( ${ctrList} )\n`;
		}
		return rStr;
	}
}

class OpenjscadWrite {
	//constructor() {}
	getHeader(): string {
		const rStr = `// Generated by Parametrix
const { polygon } = require('@jscad/modeling').primitives
//const { subtract } = require('@jscad/modeling').booleans;
const { union, intersect, scission, subtract } = require('@jscad/modeling').booleans
const { extrudeLinear, extrudeRotate } = require('@jscad/modeling').extrusions;
const { translate, rotate } = require('@jscad/modeling').transforms
const main = () => {
`;
		return rStr;
	}
	getOneFigure(aCtr: Array<tContour>, faceId: string): string {
		const ojscadWF = new OjscadWriteFigure();
		for (const ctr of aCtr) {
			ojscadWF.addContour(ctr.toOpenjscadSeg());
		}
		const rOjscadF = ojscadWF.getFigure(faceId);
		return rOjscadF;
	}
	getAllFigures(figs: tFaces, designName: string): string {
		let rStr = '';
		for (const face in figs) {
			const figu = this.getOneFigure(figs[face].mainList, `${designName}_${face}`);
			rStr += figu;
		}
		return rStr;
	}
	getOneExtrude(extrud: tExtrude): string {
		let extrudMethod = 'extrudeRotate';
		let extrudOption = '{segments: 32}';
		if (extrud.extrudeMethod === EExtrude.eLinearOrtho) {
			if (extrud.length === undefined) {
				console.log('err079: design error: extrudeLinear length undefined!');
			}
			extrudMethod = 'extrudeLinear';
			extrudOption = `{height: ${extrud.length}}`;
		}
		const rStr = `
const ${extrud.outName} =
	translate( [ ${extrud.translate[0]}, ${extrud.translate[1]}, ${extrud.translate[2]}, ],
		rotate( [ ${extrud.rotate[0]}, ${extrud.rotate[1]}, ${extrud.rotate[2]}, ],
			   ${extrudMethod}( ${extrudOption}, face_${extrud.face} )
		)
	);
`;
		return rStr;
	}
	getAllExtrudes(extrudes: Array<tExtrude>): string {
		let rStr = '';
		for (const extrud of extrudes) {
			const subp = this.getOneExtrude(extrud);
			rStr += subp;
		}
		return rStr;
	}
	getOneVolume(volum: tBVolume): string {
		let vMethod = 'identity';
		switch (volum.boolMethod) {
			case EBVolume.eIntersection:
				vMethod = 'intersect';
				break;
			case EBVolume.eUnion:
				vMethod = 'union';
				break;
			case EBVolume.eSubstraction:
				vMethod = 'substract';
				break;
		}
		const inList2 = volum.inList.join(', ');
		let rStr = `const ${volum.outName} = ${vMethod}( ${inList2} );`;
		if (volum.boolMethod === EBVolume.eIdentity) {
			rStr = `const ${volum.outName} = ${inList2};`;
		}
		return rStr;
	}
	getAllVolumes(volumes: Array<tBVolume>): string {
		let rStr = '';
		for (const volum of volumes) {
			const subp = this.getOneVolume(volum);
			rStr += subp;
		}
		return rStr;
	}
	getVolume(vol: tVolume): string {
		let rStr = '';
		rStr += this.getAllExtrudes(vol.extrudes);
		rStr += this.getAllVolumes(vol.volumes);
		return rStr;
	}
	getFooter(designName: string): string {
		const rStr = `
  return pax_${designName};
}
module.exports = { main };
`;
		return rStr;
	}
	getExportFile(figs: tFaces, volum: tVolume, designName: string) {
		let rStr = this.getHeader();
		rStr += this.getAllFigures(figs, designName);
		rStr += this.getVolume(volum);
		rStr += this.getFooter(designName);
		return rStr;
	}
}
function ojscadWrite() {
	const rOjscadWrite = new OpenjscadWrite();
	return rOjscadWrite;
}

export { ojscadWrite };
