# build_and_deploy_parametrix.yml

name: Build and Deploy Parametrix
on: [push]
jobs:
    build-and-deploy:
        concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - run: npm -w geometrix run ci
            - run: npm -w designix run ci
            - run: npm -w parametrix run ci

            - name: Build and check Parametrix
              run: |
                  npm -w geometrix run build
                  npm -w designix run build
                  npm -w parametrix run build
                  npm -w parametrix run github-pages-fix
                  npm -w parametrix run check
                  npm -w parametrix run test:unit
                  npm -w parametrix run lint

            - name: Deploy Parametrix to GitHub pages
              uses: crazy-max/ghaction-github-pages@v3
              with:
                  target_branch: gh-pages
                  build_dir: build
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
